version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5755:5755"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media